taskid: InvisibleWatermark_03
result: test_results/InvisibleWatermark_03/results.jsonl
output_dir: output/InvisibleWatermark_03/
groundtruth: groundtruth/InvisibleWatermark_03/gt.png
test_script: test_scripts/InvisibleWatermark_03/test_script.py
multi_output: false
parameters:
 watermark: 'watermark'